name: 🔮 Suggestions
description: For suggesting changes / additions / mods
title: "[Suggestion]: "
labels: [Suggestion]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out the feature request!
  - type: checkboxes
    id: Modpack
    attributes:
      label: Modpack
      description: Please select what modpack this Suggestions is for.
      options:
        - label: Age of Fate - 1.16.5
        - label: Age of Fate - 1.19.2
        - label: Age of Fate - The Frozen Hope - 1.16.5
        - label: Age of Fate - The Frozen Hope - 1.18.2
        - label: Cozy Legends - 1.19.2
        - label: Cozy Legends - 1.20.1
        - label: Crafting Legends - 1.19.2
        - label: Crafting Legends - 1.20.1
        - label: Dimensions & Dungeoneering - 1.16.5
        - label: Dimensions & Dungeoneering - 1.19.2
        - label: Dimensions & Dungeoneering - 1.20.1
        - label: Fun Filled Adventure - 1.19.2
        - label: Fun Filed Adventure - 1.20.1
        - label: Isola - 1.19.2
        - label: Isola - 1.20.1
        - label: Jurassic World Reborn II- 1.12.2
        - label: Jurassic World Reborn 2 LITE - 1.12.2
        - label: Monumental Experience - 1.19.2
        - label: Monumental Experience - 1.20.1
        - label: Monumental Experience - 1.21
        - label: Monumental Experience - In the Sky - 1.20.1
        - label: Overloaded - 1.19.2
        - label: Overloaded - 1.20.1
        - label: Overloaded Lite - 1.19.2
        - label: Overloaded Lite - 1.20.1
        - label: Tech Revolution - 1.19.2
    validations:
      required: false
  - type: checkboxes
    id: general-info
    attributes:
      label: General Info
      description: You may select more than one.
      options:
        - label: I would like to suggest a new mod
        - label: I would like to suggest a new quests
        - label: I would like to propose changes
        - label: I would like to propose another thing
    validations:
      required: false
  - type: textarea
    id: suggestion-description
    attributes:
      label: Suggestion Description
      description: Tell us your suggestion
      placeholder: I want ...
    validations:
      required: true
